function savefiles_all(filename, lhs_tops,  shs_tops,   rhos_tops,  tsas_tops,    qs_tops ,       ufs_tops,         psurfs_tops, ...
            fsnos_tops , tvs_tops ,  fpsns_tops ,     fsrs_tops,         fsas_tops,   fires_tops , ...
            lhs_pps,  shs_pps,   rhos_pps,  tsas_pps,    qs_pps ,       ufs_pps,         psurfs_pps, ...
            fsnos_pps , tvs_pps ,  fpsns_pps ,     fsrs_pps,         fsas_pps,   fires_pps,...
            BSAs_tops, WSAs_tops, albedos_tops, ...
            BSAs_pps, WSAs_pps, albedos_pps) 
save(filename, 'lhs_tops',  'shs_tops',   'rhos_tops',  'tsas_tops',    'qs_tops' ,       'ufs_tops',         'psurfs_tops', ...
            'fsnos_tops' , 'tvs_tops' ,  'fpsns_tops' ,     'fsrs_tops',         'fsas_tops',   'fires_tops' , ...
            'lhs_pps',  'shs_pps',   'rhos_pps',  'tsas_pps',    'qs_pps' ,       'ufs_pps',         'psurfs_pps', ...
            'fsnos_pps' , 'tvs_pps' ,  'fpsns_pps' ,     'fsrs_pps',         'fsas_pps',   'fires_pps',...
            'BSAs_tops', 'WSAs_tops', 'albedos_tops', ...
            'BSAs_pps', 'WSAs_pps', 'albedos_pps');