function savefile(filename, wp2_hom_pp_default, thlp2_hom_pp_default, rtp2_hom_pp_default, rtpthlp_hom_pp_default,...
        wp2_het_pp_default, thlp2_het_pp_default, rtp2_het_pp_default, rtpthlp_het_pp_default, ...
        wp2_hom_pp_topunit, thlp2_hom_pp_topunit, rtp2_hom_pp_topunit, rtpthlp_hom_pp_topunit,...
        wp2_het_pp_topunit, thlp2_het_pp_topunit, rtp2_het_pp_topunit, rtpthlp_het_pp_topunit, ...
        wp2_hom_pp_1km, thlp2_hom_pp_1km, rtp2_hom_pp_1km, rtpthlp_hom_pp_1km,...
        wp2_het_pp_1km, thlp2_het_pp_1km, rtp2_het_pp_1km, rtpthlp_het_pp_1km)
save(filename,'wp2_hom_pp_default', 'thlp2_hom_pp_default', 'rtp2_hom_pp_default', 'rtpthlp_hom_pp_default',...
        'wp2_het_pp_default', 'thlp2_het_pp_default', 'rtp2_het_pp_default', 'rtpthlp_het_pp_default', ...
        'wp2_hom_pp_topunit', 'thlp2_hom_pp_topunit', 'rtp2_hom_pp_topunit', 'rtpthlp_hom_pp_topunit',...
        'wp2_het_pp_topunit', 'thlp2_het_pp_topunit', 'rtp2_het_pp_topunit', 'rtpthlp_het_pp_topunit', ...
        'wp2_hom_pp_1km', 'thlp2_hom_pp_1km', 'rtp2_hom_pp_1km', 'rtpthlp_hom_pp_1km',...
        'wp2_het_pp_1km', 'thlp2_het_pp_1km', 'rtp2_het_pp_1km', 'rtpthlp_het_pp_1km' ...
        );